"""Object-themed 16x16 pixel art icons (GBA-era fidelity)."""

from __future__ import annotations

from src.game.icons._palette import (
    BLUE,
    DARK,
    FLAME,
    GOLD,
    INK,
    PARCHMENT,
    WHITE,
    blend_colors,
)

# ---------------------------------------------------------------------------
# Convenience aliases for 4-step ramp access
# ---------------------------------------------------------------------------
_Gh, _Gb, _Gs, _Gd = GOLD  # gold highlight / base / shadow / deep
_Fh, _Fb, _Fs, _Fd = FLAME  # flame highlight / base / shadow / deep
_Ph, _Pb, _Ps, _Pd = PARCHMENT  # parchment highlight / base / shadow / deep
_Ih, _Ib, _Is, _Id = INK  # ink highlight / base / shadow / deep
_Bh, _Bb, _Bs, _Bd = BLUE  # blue highlight / base / shadow / deep
_W = WHITE
_D = DARK

# Anti-alias blends
_aa_ink_parch = blend_colors(_Id, _Pb, 0.5)  # outline-to-face transition
_aa_ink_gold = blend_colors(_Id, _Gb, 0.5)  # outline-to-gold transition
_aa_gold_dark = blend_colors(_Gd, _D, 0.5)  # gold-into-dark transition
_aa_flame_gold = blend_colors(_Fb, _Gb, 0.5)  # flame-to-gold blend
_aa_blue_parch = blend_colors(_Bb, _Ph, 0.4)  # glass highlight
_aa_parch_ink = blend_colors(_Ps, _Is, 0.5)  # parch shadow to ink
_aa_ink_dark = blend_colors(_Is, _D, 0.5)  # ink-to-dark hole edge
_aa_gold_ink = blend_colors(_Gb, _Ib, 0.5)  # gold-to-ink metallic
_aa_key_edge = blend_colors(_Gh, _W, 0.3)  # bright key specular


def register_icons(register) -> None:  # noqa: C901
    """Register all object-themed icons."""

    # ------------------------------------------------------------------
    # 1. clock -- round clock face with hour/minute hands
    # ------------------------------------------------------------------
    register(
        "clock",
        [
            # Outer dark outline -- circular shape
            #   top arc
            (5, 0, _Id),
            (6, 0, _Id),
            (7, 0, _Id),
            (8, 0, _Id),
            (9, 0, _Id),
            (10, 0, _Id),
            (4, 1, _Id),
            (11, 1, _Id),
            (3, 2, _Id),
            (12, 2, _Id),
            (2, 3, _Id),
            (13, 3, _Id),
            (2, 4, _Id),
            (13, 4, _Id),
            (1, 5, _Id),
            (14, 5, _Id),
            (1, 6, _Id),
            (14, 6, _Id),
            (1, 7, _Id),
            (14, 7, _Id),
            (1, 8, _Id),
            (14, 8, _Id),
            (1, 9, _Id),
            (14, 9, _Id),
            (1, 10, _Id),
            (14, 10, _Id),
            (2, 11, _Id),
            (13, 11, _Id),
            (2, 12, _Id),
            (13, 12, _Id),
            (3, 13, _Id),
            (12, 13, _Id),
            (4, 14, _Id),
            (11, 14, _Id),
            (5, 15, _Id),
            (6, 15, _Id),
            (7, 15, _Id),
            (8, 15, _Id),
            (9, 15, _Id),
            (10, 15, _Id),
            # Anti-alias corners
            (4, 0, _aa_ink_parch),
            (11, 0, _aa_ink_parch),
            (3, 1, _aa_ink_parch),
            (12, 1, _aa_ink_parch),
            (2, 2, _aa_ink_parch),
            (13, 2, _aa_ink_parch),
            (3, 14, _aa_ink_parch),
            (12, 14, _aa_ink_parch),
            (4, 15, _aa_ink_parch),
            (11, 15, _aa_ink_parch),
            # Face fill -- parchment highlight top-left, base middle, shadow bottom-right
            # Row 1 interior
            (5, 1, _Ph),
            (6, 1, _Ph),
            (7, 1, _Ph),
            (8, 1, _Ph),
            (9, 1, _Ph),
            (10, 1, _Ph),
            # Row 2
            (4, 2, _Ph),
            (5, 2, _Ph),
            (6, 2, _Ph),
            (7, 2, _Ph),
            (8, 2, _Pb),
            (9, 2, _Pb),
            (10, 2, _Pb),
            (11, 2, _Pb),
            # Row 3
            (3, 3, _Ph),
            (4, 3, _Ph),
            (5, 3, _Ph),
            (6, 3, _Ph),
            (7, 3, _Ph),
            (8, 3, _Pb),
            (9, 3, _Pb),
            (10, 3, _Pb),
            (11, 3, _Pb),
            (12, 3, _Pb),
            # Row 4
            (3, 4, _Ph),
            (4, 4, _Ph),
            (5, 4, _Ph),
            (6, 4, _Ph),
            (7, 4, _Ph),
            (8, 4, _Pb),
            (9, 4, _Pb),
            (10, 4, _Pb),
            (11, 4, _Pb),
            (12, 4, _Pb),
            # Row 5
            (2, 5, _Ph),
            (3, 5, _Ph),
            (4, 5, _Ph),
            (5, 5, _Ph),
            (6, 5, _Ph),
            (7, 5, _Pb),
            (8, 5, _Pb),
            (9, 5, _Pb),
            (10, 5, _Pb),
            (11, 5, _Pb),
            (12, 5, _Pb),
            (13, 5, _Pb),
            # Row 6
            (2, 6, _Ph),
            (3, 6, _Ph),
            (4, 6, _Pb),
            (5, 6, _Pb),
            (6, 6, _Pb),
            (7, 6, _Pb),
            (8, 6, _Pb),
            (9, 6, _Pb),
            (10, 6, _Pb),
            (11, 6, _Pb),
            (12, 6, _Pb),
            (13, 6, _Pb),
            # Row 7 (center row)
            (2, 7, _Pb),
            (3, 7, _Pb),
            (4, 7, _Pb),
            (5, 7, _Pb),
            (6, 7, _Pb),
            (7, 7, _Pb),
            (8, 7, _Pb),
            (9, 7, _Pb),
            (10, 7, _Pb),
            (11, 7, _Pb),
            (12, 7, _Pb),
            (13, 7, _Pb),
            # Row 8
            (2, 8, _Pb),
            (3, 8, _Pb),
            (4, 8, _Pb),
            (5, 8, _Pb),
            (6, 8, _Pb),
            (7, 8, _Pb),
            (8, 8, _Pb),
            (9, 8, _Pb),
            (10, 8, _Pb),
            (11, 8, _Ps),
            (12, 8, _Ps),
            (13, 8, _Ps),
            # Row 9
            (2, 9, _Pb),
            (3, 9, _Pb),
            (4, 9, _Pb),
            (5, 9, _Pb),
            (6, 9, _Pb),
            (7, 9, _Pb),
            (8, 9, _Pb),
            (9, 9, _Ps),
            (10, 9, _Ps),
            (11, 9, _Ps),
            (12, 9, _Ps),
            (13, 9, _Ps),
            # Row 10
            (2, 10, _Pb),
            (3, 10, _Pb),
            (4, 10, _Pb),
            (5, 10, _Pb),
            (6, 10, _Pb),
            (7, 10, _Ps),
            (8, 10, _Ps),
            (9, 10, _Ps),
            (10, 10, _Ps),
            (11, 10, _Ps),
            (12, 10, _Ps),
            (13, 10, _Ps),
            # Row 11
            (3, 11, _Pb),
            (4, 11, _Pb),
            (5, 11, _Ps),
            (6, 11, _Ps),
            (7, 11, _Ps),
            (8, 11, _Ps),
            (9, 11, _Ps),
            (10, 11, _Ps),
            (11, 11, _Ps),
            (12, 11, _Ps),
            # Row 12
            (3, 12, _Ps),
            (4, 12, _Ps),
            (5, 12, _Ps),
            (6, 12, _Ps),
            (7, 12, _Ps),
            (8, 12, _Ps),
            (9, 12, _Ps),
            (10, 12, _Ps),
            (11, 12, _Ps),
            (12, 12, _Ps),
            # Row 13
            (4, 13, _Ps),
            (5, 13, _Ps),
            (6, 13, _Ps),
            (7, 13, _Ps),
            (8, 13, _Ps),
            (9, 13, _Ps),
            (10, 13, _Ps),
            (11, 13, _Ps),
            # Row 14
            (5, 14, _Ps),
            (6, 14, _Ps),
            (7, 14, _Pd),
            (8, 14, _Pd),
            (9, 14, _Pd),
            (10, 14, _Pd),
            # Tick marks at 12, 3, 6, 9 o'clock
            (7, 2, _Is),
            (8, 2, _Is),  # 12 o'clock
            (12, 7, _Is),
            (12, 8, _Is),  # 3 o'clock
            (7, 13, _Is),
            (8, 13, _Is),  # 6 o'clock
            (3, 7, _Is),
            (3, 8, _Is),  # 9 o'clock
            # Hour hand pointing toward ~10 (upper-left)
            (7, 7, _Gs),
            (6, 6, _Gs),
            (5, 5, _Gd),
            (4, 4, _Gd),
            # Minute hand pointing toward ~2 (upper-right)
            (8, 7, _Gs),
            (9, 6, _Gs),
            (10, 5, _Gd),
            (11, 4, _Gd),
            # Center dot
            (7, 8, _Gb),
            (8, 8, _Gb),
            (8, 7, _Gb),
        ],
    )

    # ------------------------------------------------------------------
    # 2. search -- magnifying glass with glass effect
    # ------------------------------------------------------------------
    register(
        "search",
        [
            # Lens outer dark outline (circle centered ~5,5, radius ~4)
            (4, 0, _Id),
            (5, 0, _Id),
            (6, 0, _Id),
            (7, 0, _Id),
            (3, 1, _Id),
            (8, 1, _Id),
            (2, 2, _Id),
            (9, 2, _Id),
            (1, 3, _Id),
            (10, 3, _Id),
            (1, 4, _Id),
            (10, 4, _Id),
            (1, 5, _Id),
            (10, 5, _Id),
            (1, 6, _Id),
            (10, 6, _Id),
            (1, 7, _Id),
            (10, 7, _Id),
            (2, 8, _Id),
            (9, 8, _Id),
            (3, 9, _Id),
            (8, 9, _Id),
            (4, 10, _Id),
            (5, 10, _Id),
            (6, 10, _Id),
            (7, 10, _Id),
            # Anti-alias lens corners
            (3, 0, _aa_ink_parch),
            (8, 0, _aa_ink_parch),
            (2, 1, _aa_ink_parch),
            (9, 1, _aa_ink_parch),
            (1, 2, _aa_ink_parch),
            (10, 2, _aa_ink_parch),
            (3, 10, _aa_ink_parch),
            (8, 10, _aa_ink_parch),
            # Inner ring (ink shadow for frame thickness)
            (4, 1, _Is),
            (5, 1, _Is),
            (6, 1, _Is),
            (7, 1, _Is),
            (3, 2, _Is),
            (8, 2, _Is),
            (2, 3, _Is),
            (9, 3, _Is),
            (2, 7, _Is),
            (9, 7, _Is),
            (3, 8, _Is),
            (8, 8, _Is),
            (4, 9, _Is),
            (5, 9, _Is),
            (6, 9, _Is),
            (7, 9, _Is),
            # Glass fill -- slight blue-parchment tint
            # Row 2 interior
            (4, 2, _Ph),
            (5, 2, _Ph),
            (6, 2, _Ph),
            (7, 2, _Ph),
            # Row 3
            (3, 3, _Ph),
            (4, 3, _Ph),
            (5, 3, _Pb),
            (6, 3, _Pb),
            (7, 3, _Pb),
            (8, 3, _Pb),
            # Row 4
            (2, 4, _Ph),
            (3, 4, _Pb),
            (4, 4, _Pb),
            (5, 4, _Pb),
            (6, 4, _Pb),
            (7, 4, _Pb),
            (8, 4, _Pb),
            (9, 4, _Pb),
            # Row 5
            (2, 5, _Pb),
            (3, 5, _Pb),
            (4, 5, _Pb),
            (5, 5, _Pb),
            (6, 5, _Pb),
            (7, 5, _Pb),
            (8, 5, _Pb),
            (9, 5, _Pb),
            # Row 6
            (2, 6, _Pb),
            (3, 6, _Pb),
            (4, 6, _Pb),
            (5, 6, _Pb),
            (6, 6, _Ps),
            (7, 6, _Ps),
            (8, 6, _Ps),
            (9, 6, _Ps),
            # Row 7
            (3, 7, _Ps),
            (4, 7, _Ps),
            (5, 7, _Ps),
            (6, 7, _Ps),
            (7, 7, _Ps),
            (8, 7, _Ps),
            # Glass gleam highlight (upper-left of lens)
            (3, 2, _W),
            (4, 3, _W),
            (3, 3, _aa_blue_parch),
            # Handle -- extends lower-right from lens at ~45 degrees
            (8, 9, _Gs),
            (9, 9, _Gd),
            (9, 10, _Gh),
            (10, 10, _Gs),
            (10, 9, _aa_ink_gold),
            (10, 11, _Gh),
            (11, 11, _Gs),
            (11, 10, _Gd),
            (11, 12, _Gh),
            (12, 12, _Gb),
            (12, 11, _Gd),
            (12, 13, _Gh),
            (13, 13, _Gb),
            (13, 12, _Gd),
            (13, 14, _Gb),
            (14, 14, _Gs),
            (14, 13, _Gd),
            (14, 15, _Gs),
            (15, 15, _Gd),
            (15, 14, _Gd),
            # Handle shadow edge (bottom of handle)
            (10, 12, _Gd),
            (11, 13, _Gd),
            (12, 14, _Gd),
            (13, 15, _Gd),
        ],
    )

    # ------------------------------------------------------------------
    # 3. key -- ornate brass skeleton key
    # ------------------------------------------------------------------
    register(
        "key",
        [
            # Bow (circular head) -- centered around (4, 4), radius ~3
            # Outer dark outline of bow
            (3, 0, _Gd),
            (4, 0, _Gd),
            (5, 0, _Gd),
            (6, 0, _Gd),
            (2, 1, _Gd),
            (7, 1, _Gd),
            (1, 2, _Gd),
            (8, 2, _Gd),
            (1, 3, _Gd),
            (8, 3, _Gd),
            (1, 4, _Gd),
            (8, 4, _Gd),
            (1, 5, _Gd),
            (8, 5, _Gd),
            (1, 6, _Gd),
            (8, 6, _Gd),
            (2, 7, _Gd),
            (7, 7, _Gd),
            (3, 8, _Gd),
            (4, 8, _Gd),
            (5, 8, _Gd),
            (6, 8, _Gd),
            # Anti-alias bow corners
            (2, 0, _aa_gold_dark),
            (7, 0, _aa_gold_dark),
            (1, 1, _aa_gold_dark),
            (8, 1, _aa_gold_dark),
            (1, 7, _aa_gold_dark),
            (8, 7, _aa_gold_dark),
            (2, 8, _aa_gold_dark),
            (7, 8, _aa_gold_dark),
            # Bow fill -- highlight top-left, base middle, shadow bottom-right
            (3, 1, _Gh),
            (4, 1, _Gh),
            (5, 1, _Gh),
            (6, 1, _Gb),
            (2, 2, _Gh),
            (3, 2, _Gh),
            (4, 2, _Gb),
            (5, 2, _Gb),
            (6, 2, _Gb),
            (7, 2, _Gb),
            (2, 3, _Gh),
            (3, 3, _Gb),
            (7, 3, _Gs),
            (2, 4, _Gb),
            (3, 4, _Gb),
            (7, 4, _Gs),
            (2, 5, _Gb),
            (3, 5, _Gb),
            (7, 5, _Gs),
            (2, 6, _Gb),
            (3, 6, _Gs),
            (4, 6, _Gs),
            (5, 6, _Gs),
            (6, 6, _Gs),
            (7, 6, _Gs),
            (3, 7, _Gs),
            (4, 7, _Gs),
            (5, 7, _Gs),
            (6, 7, _Gs),
            # Decorative cutout in bow center (dark hole)
            (4, 3, _D),
            (5, 3, _D),
            (6, 3, _D),
            (4, 4, _D),
            (5, 4, _D),
            (6, 4, _D),
            (4, 5, _D),
            (5, 5, _D),
            (6, 5, _D),
            # Anti-alias around cutout hole
            (4, 3, _aa_gold_dark),
            (6, 5, _aa_gold_dark),
            # Specular highlight on bow top
            (4, 1, _aa_key_edge),
            (5, 1, _aa_key_edge),
            # Shaft extending right from bow
            (8, 6, _Gd),
            (8, 7, _Gd),  # connection outline
            (9, 5, _Gd),
            (10, 5, _Gd),
            (11, 5, _Gd),
            (12, 5, _Gd),
            (13, 5, _Gd),
            (14, 5, _Gd),
            (15, 5, _Gd),
            (9, 6, _Gh),
            (10, 6, _Gh),
            (11, 6, _Gb),
            (12, 6, _Gb),
            (13, 6, _Gb),
            (14, 6, _Gb),
            (15, 6, _Gb),
            (9, 7, _Gb),
            (10, 7, _Gb),
            (11, 7, _Gs),
            (12, 7, _Gs),
            (13, 7, _Gs),
            (14, 7, _Gs),
            (15, 7, _Gs),
            (9, 8, _Gd),
            (10, 8, _Gd),
            (11, 8, _Gd),
            (12, 8, _Gd),
            (13, 8, _Gd),
            (14, 8, _Gd),
            (15, 8, _Gd),
            # Shaft specular line
            (9, 6, _aa_key_edge),
            (10, 6, _aa_key_edge),
            # Teeth at end of shaft (pointing down)
            (13, 9, _Gb),
            (13, 10, _Gb),
            (14, 9, _Gd),
            (15, 9, _Gs),
            (15, 10, _Gs),
            (15, 11, _Gs),
            (13, 11, _Gd),
            (14, 11, _Gd),
            (15, 12, _Gd),
            (14, 10, _Gd),
            # Anti-alias on teeth edges
            (12, 9, _aa_ink_gold),
            (12, 10, _aa_ink_gold),
        ],
    )

    # ------------------------------------------------------------------
    # 4. hourglass -- hourglass with flowing sand
    # ------------------------------------------------------------------
    register(
        "hourglass",
        [
            # Top frame bar
            (2, 0, _Gd),
            (3, 0, _Gd),
            (4, 0, _Gd),
            (5, 0, _Gd),
            (6, 0, _Gd),
            (7, 0, _Gd),
            (8, 0, _Gd),
            (9, 0, _Gd),
            (10, 0, _Gd),
            (11, 0, _Gd),
            (12, 0, _Gd),
            (13, 0, _Gd),
            (2, 1, _Gs),
            (3, 1, _Gh),
            (4, 1, _Gh),
            (5, 1, _Gb),
            (6, 1, _Gb),
            (7, 1, _Gb),
            (8, 1, _Gb),
            (9, 1, _Gb),
            (10, 1, _Gs),
            (11, 1, _Gs),
            (12, 1, _Gs),
            (13, 1, _Gd),
            # Top bulb outline
            (2, 2, _Id),
            (13, 2, _Id),
            (2, 3, _Id),
            (13, 3, _Id),
            (3, 4, _Id),
            (12, 4, _Id),
            (4, 5, _Id),
            (11, 5, _Id),
            (5, 6, _Id),
            (10, 6, _Id),
            (6, 7, _Id),
            (9, 7, _Id),
            # Neck
            (7, 7, _Id),
            (8, 7, _Id),
            (6, 8, _Id),
            (9, 8, _Id),
            (7, 8, _Gb),
            (8, 8, _Gb),  # sand falling through
            # Bottom bulb outline
            (5, 9, _Id),
            (10, 9, _Id),
            (4, 10, _Id),
            (11, 10, _Id),
            (3, 11, _Id),
            (12, 11, _Id),
            (2, 12, _Id),
            (13, 12, _Id),
            (2, 13, _Id),
            (13, 13, _Id),
            # Top bulb glass fill (partially emptied -- sand at bottom of top half)
            # Empty glass upper part
            (3, 2, _Ph),
            (4, 2, _Ph),
            (5, 2, _Pb),
            (6, 2, _Pb),
            (7, 2, _Pb),
            (8, 2, _Pb),
            (9, 2, _Pb),
            (10, 2, _Pb),
            (11, 2, _Ps),
            (12, 2, _Ps),
            (3, 3, _Ph),
            (4, 3, _Pb),
            (5, 3, _Pb),
            (6, 3, _Pb),
            (7, 3, _Pb),
            (8, 3, _Pb),
            (9, 3, _Pb),
            (10, 3, _Ps),
            (11, 3, _Ps),
            (12, 3, _Ps),
            # Sand remaining in top (partial fill)
            (4, 4, _Pb),
            (5, 4, _Pb),
            (6, 4, _Gh),
            (7, 4, _Gb),
            (8, 4, _Gb),
            (9, 4, _Gs),
            (10, 4, _Ps),
            (11, 4, _Ps),
            (5, 5, _Pb),
            (6, 5, _Gb),
            (7, 5, _Gb),
            (8, 5, _Gs),
            (9, 5, _Gs),
            (10, 5, _Ps),
            (6, 6, _Gb),
            (7, 6, _Gs),
            (8, 6, _Gs),
            (9, 6, _Ps),
            # Sand stream through neck
            (7, 7, _Gb),
            (8, 7, _Gs),
            # Bottom bulb -- sand accumulated
            (7, 8, _Gh),
            (8, 8, _Gb),
            (6, 9, _Pb),
            (7, 9, _Gh),
            (8, 9, _Gb),
            (9, 9, _Ps),
            (5, 10, _Pb),
            (6, 10, _Gh),
            (7, 10, _Gb),
            (8, 10, _Gb),
            (9, 10, _Gs),
            (10, 10, _Ps),
            (4, 11, _Pb),
            (5, 11, _Gh),
            (6, 11, _Gb),
            (7, 11, _Gb),
            (8, 11, _Gb),
            (9, 11, _Gs),
            (10, 11, _Gs),
            (11, 11, _Ps),
            (3, 12, _Gh),
            (4, 12, _Gh),
            (5, 12, _Gb),
            (6, 12, _Gb),
            (7, 12, _Gb),
            (8, 12, _Gb),
            (9, 12, _Gs),
            (10, 12, _Gs),
            (11, 12, _Gs),
            (12, 12, _Gs),
            (3, 13, _Gb),
            (4, 13, _Gb),
            (5, 13, _Gb),
            (6, 13, _Gb),
            (7, 13, _Gb),
            (8, 13, _Gs),
            (9, 13, _Gs),
            (10, 13, _Gs),
            (11, 13, _Gs),
            (12, 13, _Gs),
            # Bottom frame bar
            (2, 14, _Gd),
            (3, 14, _Gh),
            (4, 14, _Gh),
            (5, 14, _Gb),
            (6, 14, _Gb),
            (7, 14, _Gb),
            (8, 14, _Gb),
            (9, 14, _Gs),
            (10, 14, _Gs),
            (11, 14, _Gs),
            (12, 14, _Gs),
            (13, 14, _Gd),
            (2, 15, _Gd),
            (3, 15, _Gd),
            (4, 15, _Gd),
            (5, 15, _Gd),
            (6, 15, _Gd),
            (7, 15, _Gd),
            (8, 15, _Gd),
            (9, 15, _Gd),
            (10, 15, _Gd),
            (11, 15, _Gd),
            (12, 15, _Gd),
            (13, 15, _Gd),
            # Anti-alias transitions on glass
            (3, 4, _aa_ink_parch),
            (12, 4, _aa_ink_parch),
            (4, 5, _aa_ink_parch),
            (11, 5, _aa_ink_parch),
            (5, 9, _aa_ink_parch),
            (10, 9, _aa_ink_parch),
            (4, 10, _aa_ink_parch),
            (11, 10, _aa_ink_parch),
        ],
    )

    # ------------------------------------------------------------------
    # 5. gear -- mechanical cog with center hole and 6 teeth
    # ------------------------------------------------------------------
    register(
        "gear",
        [
            # Deep shadow outline of entire gear shape
            # Top tooth
            (6, 0, _Id),
            (7, 0, _Id),
            (8, 0, _Id),
            (9, 0, _Id),
            (6, 1, _Id),
            (9, 1, _Id),
            # Upper body connecting to top tooth
            (5, 2, _Id),
            (10, 2, _Id),
            (4, 2, _Id),
            (11, 2, _Id),
            # Upper-right tooth
            (12, 2, _Id),
            (13, 3, _Id),
            (14, 4, _Id),
            (13, 2, _Id),
            (14, 3, _Id),
            (14, 5, _Id),
            # Right side
            (14, 6, _Id),
            (15, 6, _Id),
            (15, 7, _Id),
            (15, 8, _Id),
            (15, 9, _Id),
            (14, 9, _Id),
            # Lower-right tooth
            (14, 10, _Id),
            (14, 11, _Id),
            (13, 12, _Id),
            (13, 13, _Id),
            (12, 13, _Id),
            # Bottom tooth
            (9, 14, _Id),
            (9, 15, _Id),
            (8, 15, _Id),
            (7, 15, _Id),
            (6, 15, _Id),
            (6, 14, _Id),
            (11, 13, _Id),
            (10, 13, _Id),
            # Lower-left tooth
            (4, 13, _Id),
            (3, 13, _Id),
            (3, 12, _Id),
            (2, 11, _Id),
            (1, 10, _Id),
            (1, 11, _Id),
            # Left side
            (0, 9, _Id),
            (0, 8, _Id),
            (0, 7, _Id),
            (0, 6, _Id),
            (1, 6, _Id),
            (1, 5, _Id),
            # Upper-left tooth
            (1, 4, _Id),
            (2, 3, _Id),
            (2, 2, _Id),
            (3, 2, _Id),
            (1, 3, _Id),
            # Gear body fill -- ink with parchment highlight accents on upper-left
            # Row 1 top tooth fill
            (7, 0, _Pb),
            (8, 0, _Pb),
            (7, 1, _Ih),
            (8, 1, _Ib),
            # Row 2 upper body
            (5, 2, _Ih),
            (6, 2, _Ih),
            (7, 2, _Ih),
            (8, 2, _Ib),
            (9, 2, _Ib),
            (10, 2, _Ib),
            # Rows 3-4 upper teeth and body
            (3, 3, _Pb),
            (4, 3, _Ih),
            (5, 3, _Ih),
            (6, 3, _Ih),
            (7, 3, _Ih),
            (8, 3, _Ib),
            (9, 3, _Ib),
            (10, 3, _Ib),
            (11, 3, _Ib),
            (12, 3, _Ib),
            (2, 4, _Pb),
            (3, 4, _Ih),
            (4, 4, _Ih),
            (5, 4, _Ib),
            (6, 4, _Ib),
            (7, 4, _Ib),
            (8, 4, _Ib),
            (9, 4, _Ib),
            (10, 4, _Ib),
            (11, 4, _Ib),
            (12, 4, _Ib),
            (13, 4, _Ib),
            (2, 5, _Ih),
            (3, 5, _Ib),
            (4, 5, _Ib),
            (5, 5, _Ib),
            (10, 5, _Ib),
            (11, 5, _Ib),
            (12, 5, _Ib),
            (13, 5, _Ib),
            # Row 6-9 left/right teeth and body ring
            (2, 6, _Pb),
            (3, 6, _Ib),
            (4, 6, _Ib),
            (11, 6, _Ib),
            (12, 6, _Is),
            (13, 6, _Is),
            (14, 6, _Is),
            (1, 7, _Pb),
            (2, 7, _Ib),
            (3, 7, _Ib),
            (4, 7, _Ib),
            (11, 7, _Is),
            (12, 7, _Is),
            (13, 7, _Is),
            (14, 7, _Is),
            (1, 8, _Ib),
            (2, 8, _Ib),
            (3, 8, _aa_parch_ink),
            (4, 8, _Is),
            (11, 8, _Is),
            (12, 8, _Is),
            (13, 8, _Is),
            (14, 8, _Is),
            (1, 9, _Ib),
            (2, 9, _Is),
            (3, 9, _Is),
            (4, 9, _Is),
            (11, 9, _Is),
            (12, 9, _Is),
            (13, 9, _Is),
            (2, 10, _Is),
            (3, 10, _Is),
            (4, 10, _Is),
            (5, 10, _Is),
            (10, 10, _Is),
            (11, 10, _Is),
            (12, 10, _Is),
            (13, 10, _Is),
            # Lower body
            (3, 11, _Is),
            (4, 11, _Is),
            (5, 11, _Is),
            (6, 11, _Is),
            (7, 11, _Is),
            (8, 11, _Is),
            (9, 11, _Is),
            (10, 11, _Is),
            (11, 11, _Is),
            (12, 11, _Is),
            (4, 12, _Is),
            (5, 12, _Is),
            (6, 12, _Is),
            (7, 12, _Is),
            (8, 12, _Is),
            (9, 12, _Is),
            (10, 12, _Is),
            (11, 12, _Is),
            (5, 13, _Is),
            (6, 13, _Is),
            (7, 13, _Is),
            (8, 13, _Is),
            (9, 13, _Is),
            # Bottom tooth fill
            (7, 14, _Is),
            (8, 14, _Is),
            # Anti-alias on tooth edges
            (6, 0, _aa_ink_dark),
            (9, 0, _aa_ink_dark),
            (6, 15, _aa_ink_dark),
            (9, 15, _aa_ink_dark),
            # Center hole (dark void)
            (6, 5, _D),
            (7, 5, _D),
            (8, 5, _D),
            (9, 5, _D),
            (5, 6, _D),
            (6, 6, _D),
            (7, 6, _D),
            (8, 6, _D),
            (9, 6, _D),
            (10, 6, _D),
            (5, 7, _D),
            (6, 7, _D),
            (7, 7, _D),
            (8, 7, _D),
            (9, 7, _D),
            (10, 7, _D),
            (5, 8, _D),
            (6, 8, _D),
            (7, 8, _D),
            (8, 8, _D),
            (9, 8, _D),
            (10, 8, _D),
            (5, 9, _D),
            (6, 9, _D),
            (7, 9, _D),
            (8, 9, _D),
            (9, 9, _D),
            (10, 9, _D),
            (6, 10, _D),
            (7, 10, _D),
            (8, 10, _D),
            (9, 10, _D),
            # Highlight rim on hole (upper-left edge)
            (6, 5, _Ih),
            (7, 5, _Ih),
            (5, 6, _Ih),
            (5, 7, _Ih),
            # Shadow rim on hole (lower-right edge)
            (10, 8, _aa_ink_dark),
            (10, 9, _aa_ink_dark),
            (9, 10, _aa_ink_dark),
        ],
    )

    # ------------------------------------------------------------------
    # 6. house -- small cottage with chimney
    # ------------------------------------------------------------------
    register(
        "house",
        [
            # Chimney on left side
            (3, 1, _Is),
            (4, 1, _Is),
            (3, 2, _Is),
            (4, 2, _Ib),
            (3, 3, _Is),
            (4, 3, _Ib),
            (3, 0, _Id),
            (4, 0, _Id),  # chimney top outline
            (2, 1, _Id),
            (2, 2, _Id),
            (2, 3, _Id),  # chimney left outline
            (5, 1, _Id),  # chimney right outline (before roof takes over)
            # Chimney smoke wisp
            (3, 0, _Ib),
            (2, 0, _Is),
            # Roof -- triangular, flame red
            # Outline
            (7, 2, _Fd),
            (8, 2, _Fd),
            (6, 3, _Fd),
            (9, 3, _Fd),
            (5, 4, _Fd),
            (10, 4, _Fd),
            (4, 5, _Fd),
            (11, 5, _Fd),
            (3, 6, _Fd),
            (12, 6, _Fd),
            (2, 7, _Fd),
            (13, 7, _Fd),
            (1, 8, _Fd),
            (14, 8, _Fd),
            # Roof fill -- highlight on left slope, shadow on right
            (7, 3, _Fh),
            (8, 3, _Fb),
            (6, 4, _Fh),
            (7, 4, _Fh),
            (8, 4, _Fb),
            (9, 4, _Fb),
            (5, 5, _Fh),
            (6, 5, _Fh),
            (7, 5, _Fb),
            (8, 5, _Fb),
            (9, 5, _Fs),
            (10, 5, _Fs),
            (4, 6, _Fh),
            (5, 6, _Fh),
            (6, 6, _Fb),
            (7, 6, _Fb),
            (8, 6, _Fb),
            (9, 6, _Fs),
            (10, 6, _Fs),
            (11, 6, _Fs),
            (3, 7, _Fh),
            (4, 7, _Fh),
            (5, 7, _Fb),
            (6, 7, _Fb),
            (7, 7, _Fb),
            (8, 7, _Fb),
            (9, 7, _Fs),
            (10, 7, _Fs),
            (11, 7, _Fs),
            (12, 7, _Fs),
            (2, 8, _Fh),
            (3, 8, _Fb),
            (4, 8, _Fb),
            (5, 8, _Fb),
            (6, 8, _Fb),
            (7, 8, _Fb),
            (8, 8, _Fb),
            (9, 8, _Fs),
            (10, 8, _Fs),
            (11, 8, _Fs),
            (12, 8, _Fs),
            (13, 8, _Fs),
            # Walls
            # Wall outline
            (2, 9, _Id),
            (13, 9, _Id),
            (2, 10, _Id),
            (13, 10, _Id),
            (2, 11, _Id),
            (13, 11, _Id),
            (2, 12, _Id),
            (13, 12, _Id),
            (2, 13, _Id),
            (13, 13, _Id),
            # Foundation
            (1, 14, _Id),
            (2, 14, _Id),
            (3, 14, _Id),
            (4, 14, _Id),
            (5, 14, _Id),
            (6, 14, _Id),
            (7, 14, _Id),
            (8, 14, _Id),
            (9, 14, _Id),
            (10, 14, _Id),
            (11, 14, _Id),
            (12, 14, _Id),
            (13, 14, _Id),
            (14, 14, _Id),
            # Wall fill
            (3, 9, _Ph),
            (4, 9, _Ph),
            (5, 9, _Pb),
            (6, 9, _Pb),
            (7, 9, _Pb),
            (8, 9, _Pb),
            (9, 9, _Pb),
            (10, 9, _Ps),
            (11, 9, _Ps),
            (12, 9, _Ps),
            (3, 10, _Ph),
            (4, 10, _Pb),
            (5, 10, _Pb),
            (6, 10, _Pb),
            (7, 10, _Pb),
            (8, 10, _Pb),
            (9, 10, _Pb),
            (10, 10, _Ps),
            (11, 10, _Ps),
            (12, 10, _Ps),
            (3, 11, _Pb),
            (4, 11, _Pb),
            (5, 11, _Pb),
            (6, 11, _Pb),
            (7, 11, _Pb),
            (8, 11, _Pb),
            (9, 11, _Pb),
            (10, 11, _Ps),
            (11, 11, _Ps),
            (12, 11, _Ps),
            (3, 12, _Pb),
            (4, 12, _Pb),
            (5, 12, _Pb),
            (6, 12, _Pb),
            (9, 12, _Pb),
            (10, 12, _Ps),
            (11, 12, _Ps),
            (12, 12, _Ps),
            (3, 13, _Pb),
            (4, 13, _Pb),
            (5, 13, _Ps),
            (6, 13, _Ps),
            (9, 13, _Ps),
            (10, 13, _Ps),
            (11, 13, _Ps),
            (12, 13, _Ps),
            # Window (left side) -- blue glass with cross frame
            (4, 10, _Bb),
            (5, 10, _Bb),
            (4, 11, _Bb),
            (5, 11, _Bb),
            (4, 10, _Bh),
            (5, 10, _Bb),  # glass highlight top-left
            (4, 11, _Bb),
            (5, 11, _Bs),  # glass shadow bottom-right
            # Window cross-frame
            (4, 10, _Id),
            (5, 10, _Id),  # top frame
            (4, 11, _Id),
            (5, 11, _Id),  # bottom frame (we'll use inner frame)
            # Reworked window: 2x2 panes with frame
            (3, 9, _Id),
            (4, 9, _Id),
            (5, 9, _Id),
            (6, 9, _Id),  # top frame
            (3, 12, _Id),
            (6, 12, _Id),  # bottom frame corners
            (3, 10, _Id),
            (6, 10, _Id),  # side frames
            (3, 11, _Id),
            (6, 11, _Id),
            (4, 10, _Bh),
            (5, 10, _Bb),  # upper panes
            (4, 11, _Bb),
            (5, 11, _Bs),  # lower panes
            # Door (center-right) -- gold/dark
            (7, 11, _Gd),
            (8, 11, _Gd),
            (9, 11, _Gd),  # door top outline
            (7, 12, _Gs),
            (8, 12, _Gb),
            (9, 12, _Gs),
            (7, 13, _Gs),
            (8, 13, _Gb),
            (9, 13, _Gd),
            (8, 12, _Gb),  # doorknob highlight
            # Door frame
            (7, 11, _Gd),
            (9, 11, _Gd),
        ],
    )

    # ------------------------------------------------------------------
    # 7. library -- classical building with pediment and columns
    # ------------------------------------------------------------------
    register(
        "library",
        [
            # Pediment (triangular top) -- gold
            (7, 0, _Gd),
            (8, 0, _Gd),
            (6, 1, _Gd),
            (9, 1, _Gd),
            (5, 2, _Gd),
            (10, 2, _Gd),
            (4, 3, _Gd),
            (11, 3, _Gd),
            (3, 4, _Gd),
            (12, 4, _Gd),
            # Pediment fill
            (7, 1, _Gh),
            (8, 1, _Gb),
            (6, 2, _Gh),
            (7, 2, _Gh),
            (8, 2, _Gb),
            (9, 2, _Gs),
            (5, 3, _Gh),
            (6, 3, _Gh),
            (7, 3, _Gb),
            (8, 3, _Gb),
            (9, 3, _Gs),
            (10, 3, _Gs),
            (4, 4, _Gh),
            (5, 4, _Gh),
            (6, 4, _Gb),
            (7, 4, _Gb),
            (8, 4, _Gb),
            (9, 4, _Gs),
            (10, 4, _Gs),
            (11, 4, _Gs),
            # Small book decoration in pediment center
            (7, 2, _Pb),
            (8, 2, _Pb),
            (7, 3, _Fs),
            (8, 3, _Fs),
            # Entablature (horizontal bar under pediment)
            (2, 5, _Gd),
            (3, 5, _Gh),
            (4, 5, _Gh),
            (5, 5, _Gb),
            (6, 5, _Gb),
            (7, 5, _Gb),
            (8, 5, _Gb),
            (9, 5, _Gs),
            (10, 5, _Gs),
            (11, 5, _Gs),
            (12, 5, _Gs),
            (13, 5, _Gd),
            (2, 6, _Gd),
            (3, 6, _Gd),
            (4, 6, _Gd),
            (5, 6, _Gd),
            (6, 6, _Gd),
            (7, 6, _Gd),
            (8, 6, _Gd),
            (9, 6, _Gd),
            (10, 6, _Gd),
            (11, 6, _Gd),
            (12, 6, _Gd),
            (13, 6, _Gd),
            # Columns (3 columns with dark gaps between)
            # Left column at x=3-4
            (3, 7, _Ph),
            (4, 7, _Ps),
            (3, 8, _Ph),
            (4, 8, _Ps),
            (3, 9, _Pb),
            (4, 9, _Ps),
            (3, 10, _Pb),
            (4, 10, _Ps),
            (3, 11, _Pb),
            (4, 11, _Ps),
            (3, 12, _Ps),
            (4, 12, _Pd),
            # Center column at x=7-8
            (7, 7, _Ph),
            (8, 7, _Ps),
            (7, 8, _Ph),
            (8, 8, _Ps),
            (7, 9, _Pb),
            (8, 9, _Ps),
            (7, 10, _Pb),
            (8, 10, _Ps),
            (7, 11, _Pb),
            (8, 11, _Ps),
            (7, 12, _Ps),
            (8, 12, _Pd),
            # Right column at x=11-12
            (11, 7, _Ph),
            (12, 7, _Ps),
            (11, 8, _Ph),
            (12, 8, _Ps),
            (11, 9, _Pb),
            (12, 9, _Ps),
            (11, 10, _Pb),
            (12, 10, _Ps),
            (11, 11, _Pb),
            (12, 11, _Ps),
            (11, 12, _Ps),
            (12, 12, _Pd),
            # Dark doorways between columns
            (5, 7, _D),
            (6, 7, _D),
            (9, 7, _D),
            (10, 7, _D),
            (5, 8, _D),
            (6, 8, _D),
            (9, 8, _D),
            (10, 8, _D),
            (5, 9, _D),
            (6, 9, _D),
            (9, 9, _D),
            (10, 9, _D),
            (5, 10, _D),
            (6, 10, _D),
            (9, 10, _D),
            (10, 10, _D),
            (5, 11, _D),
            (6, 11, _D),
            (9, 11, _D),
            (10, 11, _D),
            (5, 12, _D),
            (6, 12, _D),
            (9, 12, _D),
            (10, 12, _D),
            # Side walls
            (2, 7, _Id),
            (13, 7, _Id),
            (2, 8, _Id),
            (13, 8, _Id),
            (2, 9, _Id),
            (13, 9, _Id),
            (2, 10, _Id),
            (13, 10, _Id),
            (2, 11, _Id),
            (13, 11, _Id),
            (2, 12, _Id),
            (13, 12, _Id),
            # Steps (3 tiers)
            (2, 13, _Gs),
            (3, 13, _Gh),
            (4, 13, _Gh),
            (5, 13, _Gb),
            (6, 13, _Gb),
            (7, 13, _Gb),
            (8, 13, _Gb),
            (9, 13, _Gs),
            (10, 13, _Gs),
            (11, 13, _Gs),
            (12, 13, _Gs),
            (13, 13, _Gd),
            (1, 14, _Gs),
            (2, 14, _Gh),
            (3, 14, _Gb),
            (4, 14, _Gb),
            (5, 14, _Gb),
            (6, 14, _Gb),
            (7, 14, _Gb),
            (8, 14, _Gs),
            (9, 14, _Gs),
            (10, 14, _Gs),
            (11, 14, _Gs),
            (12, 14, _Gs),
            (13, 14, _Gs),
            (14, 14, _Gd),
            (0, 15, _Gd),
            (1, 15, _Gh),
            (2, 15, _Gb),
            (3, 15, _Gb),
            (4, 15, _Gb),
            (5, 15, _Gb),
            (6, 15, _Gb),
            (7, 15, _Gb),
            (8, 15, _Gs),
            (9, 15, _Gs),
            (10, 15, _Gs),
            (11, 15, _Gs),
            (12, 15, _Gs),
            (13, 15, _Gs),
            (14, 15, _Gs),
            (15, 15, _Gd),
        ],
    )

    # ------------------------------------------------------------------
    # 8. construction -- sawhorse barricade with diagonal stripes
    # ------------------------------------------------------------------
    register(
        "construction",
        [
            # Top rail outline
            (0, 3, _Id),
            (15, 3, _Id),
            (0, 4, _Id),
            (15, 4, _Id),
            (0, 5, _Id),
            (15, 5, _Id),
            (0, 6, _Id),
            (15, 6, _Id),
            (0, 7, _Id),
            (15, 7, _Id),
            (0, 8, _Id),
            (15, 8, _Id),
            # Top and bottom edges of rail
            (1, 2, _Id),
            (2, 2, _Id),
            (3, 2, _Id),
            (4, 2, _Id),
            (5, 2, _Id),
            (6, 2, _Id),
            (7, 2, _Id),
            (8, 2, _Id),
            (9, 2, _Id),
            (10, 2, _Id),
            (11, 2, _Id),
            (12, 2, _Id),
            (13, 2, _Id),
            (14, 2, _Id),
            (1, 9, _Id),
            (2, 9, _Id),
            (3, 9, _Id),
            (4, 9, _Id),
            (5, 9, _Id),
            (6, 9, _Id),
            (7, 9, _Id),
            (8, 9, _Id),
            (9, 9, _Id),
            (10, 9, _Id),
            (11, 9, _Id),
            (12, 9, _Id),
            (13, 9, _Id),
            (14, 9, _Id),
            # Diagonal stripes on the barricade (alternating gold and flame)
            # The stripes go from upper-left to lower-right at ~45 degrees
            # Stripe pattern: 3px gold, 3px flame, repeating
            # Row 3 (y=3)
            (1, 3, _Gh),
            (2, 3, _Gb),
            (3, 3, _Gb),
            (4, 3, _Fh),
            (5, 3, _Fb),
            (6, 3, _Fb),
            (7, 3, _Gh),
            (8, 3, _Gb),
            (9, 3, _Gb),
            (10, 3, _Fh),
            (11, 3, _Fb),
            (12, 3, _Fb),
            (13, 3, _Gh),
            (14, 3, _Gb),
            # Row 4 (y=4) -- stripes shift right by 1
            (1, 4, _Fs),
            (2, 4, _Gh),
            (3, 4, _Gb),
            (4, 4, _Gb),
            (5, 4, _Fh),
            (6, 4, _Fb),
            (7, 4, _Fb),
            (8, 4, _Gh),
            (9, 4, _Gb),
            (10, 4, _Gb),
            (11, 4, _Fh),
            (12, 4, _Fb),
            (13, 4, _Fb),
            (14, 4, _Gh),
            # Row 5 (y=5) -- shift right by 2
            (1, 5, _Fs),
            (2, 5, _Fs),
            (3, 5, _Gh),
            (4, 5, _Gb),
            (5, 5, _Gb),
            (6, 5, _Fh),
            (7, 5, _Fb),
            (8, 5, _Fb),
            (9, 5, _Gh),
            (10, 5, _Gb),
            (11, 5, _Gb),
            (12, 5, _Fh),
            (13, 5, _Fb),
            (14, 5, _Fb),
            # Row 6 (y=6) -- shift right by 3 (same as row 3 offset by half period)
            (1, 6, _Fb),
            (2, 6, _Fs),
            (3, 6, _Fs),
            (4, 6, _Gh),
            (5, 6, _Gb),
            (6, 6, _Gb),
            (7, 6, _Fh),
            (8, 6, _Fb),
            (9, 6, _Fs),
            (10, 6, _Gh),
            (11, 6, _Gb),
            (12, 6, _Gb),
            (13, 6, _Fh),
            (14, 6, _Fb),
            # Row 7 (y=7) -- shift right by 4
            (1, 7, _Gb),
            (2, 7, _Fb),
            (3, 7, _Fs),
            (4, 7, _Fs),
            (5, 7, _Gh),
            (6, 7, _Gb),
            (7, 7, _Gb),
            (8, 7, _Fh),
            (9, 7, _Fb),
            (10, 7, _Fs),
            (11, 7, _Gh),
            (12, 7, _Gb),
            (13, 7, _Gb),
            (14, 7, _Fh),
            # Row 8 (y=8) -- shift right by 5
            (1, 8, _Gb),
            (2, 8, _Gs),
            (3, 8, _Fb),
            (4, 8, _Fs),
            (5, 8, _Fs),
            (6, 8, _Gh),
            (7, 8, _Gb),
            (8, 8, _Gs),
            (9, 8, _Fh),
            (10, 8, _Fb),
            (11, 8, _Fs),
            (12, 8, _Gh),
            (13, 8, _Gb),
            (14, 8, _Gs),
            # Sawhorse legs -- A-frame supports
            # Left leg (from rail down-left)
            (3, 10, _Is),
            (4, 10, _Ib),
            (2, 11, _Is),
            (3, 11, _Ib),
            (1, 12, _Is),
            (2, 12, _Ib),
            (0, 13, _Is),
            (1, 13, _Ib),
            (0, 14, _Id),
            (1, 14, _Id),
            # Left inner leg (from rail down-right slightly)
            (5, 10, _Ib),
            (6, 10, _Is),
            (6, 11, _Ib),
            (7, 11, _Is),
            (7, 12, _Ib),
            (8, 12, _Is),
            (8, 13, _Ib),
            (9, 13, _Is),
            (8, 14, _Id),
            (9, 14, _Id),
            # Right inner leg (from rail down-left slightly)
            (9, 10, _Ib),
            (10, 10, _Is),
            (8, 11, _Ib),
            (9, 11, _Is),
            # (shares pixels with left inner leg at y=12,13)
            # Right leg (from rail down-right)
            (11, 10, _Ib),
            (12, 10, _Is),
            (12, 11, _Ib),
            (13, 11, _Is),
            (13, 12, _Ib),
            (14, 12, _Is),
            (14, 13, _Ib),
            (15, 13, _Is),
            (14, 14, _Id),
            (15, 14, _Id),
            # Cross brace between legs
            (3, 12, _Ib),
            (4, 12, _Ib),
            (5, 12, _Ib),
            (6, 12, _Ib),
            (10, 12, _Ib),
            (11, 12, _Ib),
            (12, 12, _Ib),
            # Feet / ground line
            (0, 15, _Id),
            (1, 15, _Id),
            (8, 15, _Id),
            (9, 15, _Id),
            (14, 15, _Id),
            (15, 15, _Id),
        ],
    )
